
# Link LaunchSettings.json url to our entry in Program.cs on game server for a GET method 
# has to do with Huachao Mao's REST client Extension for VSCODE
@baseURL = http://localhost:5030

GET {{baseURL}}/games

### 
GET {{baseURL}}/games/1

### 
POST {{baseURL}}/games
content-type: application/json

{
  "gameName": "Test Game 1",
  "genre": "Platformer",
  "price": 19.99,
  "releaseDate": "2001-01-11"
}